server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启Eureka服务发现
          lower-case-service-id: true
      routes:
        - id: user-service #路由标识必须唯一
          uri: lb://userservice #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #路由断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true